name: CI
on:
  workflow_dispatch:
    branches: [ master, actions ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo Hello, world 1!